/**
 * React PDF template for the Prism AI Chargeback Report.
 * Rendered server-side via @react-pdf/renderer.
 */
import React from "react";
import {
  Document, Page, Text, View, StyleSheet, Font,
} from "@react-pdf/renderer";
import type { ChargebackReportData } from "./chargeback";

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmtCost(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000)     return `$${(n / 1_000).toFixed(2)}K`;
  return `$${n.toFixed(4)}`;
}

function fmtPct(n: number | null): string {
  if (n === null) return "N/A";
  const sign = n >= 0 ? "+" : "";
  return `${sign}${n.toFixed(1)}%`;
}

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    year: "numeric", month: "short", day: "numeric", timeZone: "UTC",
  });
}

// ── Styles ────────────────────────────────────────────────────────────────────

const C = {
  bg:       "#09090b",
  surface:  "#18181b",
  border:   "#27272a",
  text:     "#e4e4e7",
  muted:    "#71717a",
  indigo:   "#6366f1",
  emerald:  "#10b981",
  amber:    "#f59e0b",
  red:      "#ef4444",
  white:    "#ffffff",
};

const s = StyleSheet.create({
  page:         { backgroundColor: C.bg, padding: 40, fontFamily: "Helvetica" },
  // Cover
  cover:        { flex: 1, justifyContent: "center" },
  coverTag:     { color: C.indigo, fontSize: 9, letterSpacing: 2, textTransform: "uppercase", marginBottom: 12 },
  coverTitle:   { color: C.white, fontSize: 28, fontFamily: "Helvetica-Bold", marginBottom: 8 },
  coverSub:     { color: C.muted, fontSize: 12 },
  coverLine:    { height: 2, backgroundColor: C.indigo, width: 48, marginBottom: 20 },
  coverMeta:    { marginTop: 40, flexDirection: "row", gap: 24 },
  coverMetaBox: { backgroundColor: C.surface, borderRadius: 6, padding: 12, flex: 1 },
  coverMetaLbl: { color: C.muted, fontSize: 8, textTransform: "uppercase", letterSpacing: 1, marginBottom: 4 },
  coverMetaVal: { color: C.white, fontSize: 14, fontFamily: "Helvetica-Bold" },
  coverMetaSub: { color: C.muted, fontSize: 8, marginTop: 2 },
  // Section
  section:      { marginTop: 28 },
  sectionHdr:   { color: C.indigo, fontSize: 8, textTransform: "uppercase", letterSpacing: 2, marginBottom: 10, borderBottom: `1px solid ${C.border}`, paddingBottom: 4 },
  // Table
  table:        { width: "100%" },
  thead:        { flexDirection: "row", backgroundColor: C.surface, borderRadius: 4, paddingVertical: 5, paddingHorizontal: 8, marginBottom: 2 },
  theadCell:    { color: C.muted, fontSize: 7, textTransform: "uppercase", flex: 1 },
  theadRight:   { color: C.muted, fontSize: 7, textTransform: "uppercase", flex: 1, textAlign: "right" },
  tbody:        { gap: 1 },
  trow:         { flexDirection: "row", paddingVertical: 5, paddingHorizontal: 8, borderRadius: 3 },
  trowAlt:      { flexDirection: "row", paddingVertical: 5, paddingHorizontal: 8, borderRadius: 3, backgroundColor: `${C.surface}80` },
  tcell:        { color: C.text, fontSize: 8, flex: 1 },
  tcellRight:   { color: C.text, fontSize: 8, flex: 1, textAlign: "right" },
  tcellMuted:   { color: C.muted, fontSize: 8, flex: 1, textAlign: "right" },
  // Footer
  footer:       { position: "absolute", bottom: 24, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between" },
  footerText:   { color: C.muted, fontSize: 7 },
});

// ── Components ────────────────────────────────────────────────────────────────

function Footer({ orgName, pageNum }: { orgName: string; pageNum: number }) {
  return (
    <View style={s.footer} fixed>
      <Text style={s.footerText}>Generated by Prism · {orgName}</Text>
      <Text style={s.footerText}>Page {pageNum}</Text>
    </View>
  );
}

function SectionHeader({ title }: { title: string }) {
  return <Text style={s.sectionHdr}>{title}</Text>;
}

// ── Main Document ─────────────────────────────────────────────────────────────

export function ChargebackPdf({ data }: { data: ChargebackReportData }) {
  const { summary } = data;

  return (
    <Document>
      {/* ── Cover page ──────────────────────────────────────────────────────── */}
      <Page size="A4" style={s.page}>
        <View style={s.cover}>
          <Text style={s.coverTag}>AI FinOps · Chargeback Report</Text>
          <View style={s.coverLine} />
          <Text style={s.coverTitle}>{data.org_name}</Text>
          <Text style={s.coverSub}>{data.period.label}</Text>

          <View style={s.coverMeta}>
            <View style={s.coverMetaBox}>
              <Text style={s.coverMetaLbl}>Total AI Spend</Text>
              <Text style={s.coverMetaVal}>{fmtCost(summary.total_cost_usd)}</Text>
              {summary.mom_delta_pct !== null && (
                <Text style={[s.coverMetaSub, { color: summary.mom_delta_pct > 0 ? C.red : C.emerald }]}>
                  {fmtPct(summary.mom_delta_pct)} vs. prior period
                </Text>
              )}
            </View>
            <View style={s.coverMetaBox}>
              <Text style={s.coverMetaLbl}>Providers</Text>
              <Text style={s.coverMetaVal}>{summary.provider_count}</Text>
              <Text style={s.coverMetaSub}>{data.by_vendor.map(v => v.provider).join(", ")}</Text>
            </View>
            <View style={s.coverMetaBox}>
              <Text style={s.coverMetaLbl}>Total Requests</Text>
              <Text style={s.coverMetaVal}>{summary.request_count.toLocaleString()}</Text>
              <Text style={s.coverMetaSub}>{fmtDate(data.period.from)} – {fmtDate(data.period.to)}</Text>
            </View>
          </View>
        </View>
        <Footer orgName={data.org_name} pageNum={1} />
      </Page>

      {/* ── Vendor Breakdown ────────────────────────────────────────────────── */}
      <Page size="A4" style={s.page}>
        <View style={s.section}>
          <SectionHeader title="Vendor Spend Breakdown" />
          <View style={s.table}>
            <View style={s.thead}>
              <Text style={s.theadCell}>Provider</Text>
              <Text style={s.theadRight}>Requests</Text>
              <Text style={s.theadRight}>Total Spend</Text>
              <Text style={s.theadRight}>Cost / 1M Tokens</Text>
              <Text style={s.theadRight}>% of Total</Text>
            </View>
            <View style={s.tbody}>
              {data.by_vendor.map((v, i) => {
                const pct = summary.total_cost_usd > 0
                  ? (v.total_cost_usd / summary.total_cost_usd) * 100 : 0;
                return (
                  <View key={v.provider} style={i % 2 === 0 ? s.trow : s.trowAlt}>
                    <Text style={[s.tcell, { fontFamily: "Helvetica-Bold" }]}>{v.provider}</Text>
                    <Text style={s.tcellRight}>{v.total_requests.toLocaleString()}</Text>
                    <Text style={[s.tcellRight, { color: C.indigo, fontFamily: "Helvetica-Bold" }]}>{fmtCost(v.total_cost_usd)}</Text>
                    <Text style={s.tcellMuted}>{fmtCost(v.cost_per_1m_tokens ?? 0)}</Text>
                    <Text style={s.tcellMuted}>{pct.toFixed(1)}%</Text>
                  </View>
                );
              })}
            </View>
          </View>
        </View>

        {/* ── Cost Center Chargeback ─────────────────────────────────────────── */}
        {data.by_cost_center.length > 0 && (
          <View style={s.section}>
            <SectionHeader title="Cost Center Chargeback" />
            <View style={s.table}>
              <View style={s.thead}>
                <Text style={[s.theadCell, { flex: 2 }]}>Cost Center / GL Code</Text>
                <Text style={s.theadRight}>Projects</Text>
                <Text style={s.theadRight}>Requests</Text>
                <Text style={s.theadRight}>Total Spend</Text>
                <Text style={s.theadRight}>% of Total</Text>
              </View>
              <View style={s.tbody}>
                {data.by_cost_center.map((cc, i) => {
                  const pct = summary.total_cost_usd > 0
                    ? (cc.cost_usd / summary.total_cost_usd) * 100 : 0;
                  return (
                    <View key={cc.cost_center} style={i % 2 === 0 ? s.trow : s.trowAlt}>
                      <Text style={[s.tcell, { flex: 2, fontFamily: "Helvetica-Bold" }]}>{cc.cost_center}</Text>
                      <Text style={s.tcellRight}>{cc.project_count}</Text>
                      <Text style={s.tcellRight}>{cc.requests.toLocaleString()}</Text>
                      <Text style={[s.tcellRight, { color: C.indigo, fontFamily: "Helvetica-Bold" }]}>{fmtCost(cc.cost_usd)}</Text>
                      <Text style={s.tcellMuted}>{pct.toFixed(1)}%</Text>
                    </View>
                  );
                })}
              </View>
            </View>
          </View>
        )}

        <Footer orgName={data.org_name} pageNum={2} />
      </Page>

      {/* ── Project Breakdown ───────────────────────────────────────────────── */}
      {data.by_project.length > 0 && (
        <Page size="A4" style={s.page}>
          <View style={s.section}>
            <SectionHeader title="Project Breakdown" />
            <View style={s.table}>
              <View style={s.thead}>
                <Text style={[s.theadCell, { flex: 2 }]}>Project</Text>
                <Text style={s.theadRight}>Requests</Text>
                <Text style={s.theadRight}>Total Spend</Text>
                <Text style={s.theadRight}>Avg Latency</Text>
              </View>
              <View style={s.tbody}>
                {data.by_project.map((p, i) => (
                  <View key={p.project_id} style={i % 2 === 0 ? s.trow : s.trowAlt}>
                    <Text style={[s.tcell, { flex: 2 }]}>{p.project_name || p.project_id}</Text>
                    <Text style={s.tcellRight}>{p.requests.toLocaleString()}</Text>
                    <Text style={[s.tcellRight, { color: C.indigo }]}>{fmtCost(p.cost_usd)}</Text>
                    <Text style={s.tcellMuted}>{Math.round(p.avg_latency_ms)}ms</Text>
                  </View>
                ))}
              </View>
            </View>
          </View>
          <Footer orgName={data.org_name} pageNum={3} />
        </Page>
      )}
    </Document>
  );
}
