/**
 * GET /api/export/finops
 *
 * Returns a CFO-ready CSV with multiple sections:
 * - Section 1: Vendor spend summary
 * - Section 2: Cost center breakdown
 * - Section 3: Budget utilization
 *
 * Designed to be opened in Excel for vendor negotiation preparation.
 */

import { NextRequest, NextResponse } from "next/server";
import { createServerClient, getMemberOrg } from "@/lib/supabase/server";
import { getSpendByProvider, getSpendByCostCenter } from "@/lib/tinybird/queries";

function thirtyDaysAgo() {
  return new Date(Date.now() - 30 * 86_400_000).toISOString().replace("T", " ").slice(0, 19);
}
function today() {
  return new Date().toISOString().replace("T", " ").slice(0, 19);
}
function fmtDate() {
  return new Date().toISOString().slice(0, 10);
}

function row(...cells: (string | number | null | undefined)[]): string {
  return cells.map(c => {
    const v = c == null ? "" : String(c);
    return v.includes(",") || v.includes('"') ? `"${v.replace(/"/g, '""')}"` : v;
  }).join(",");
}

export async function GET(req: NextRequest) {
  const supabase = createServerClient();
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error || !user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const member = await getMemberOrg(user.id);
  if (!member) return NextResponse.json({ error: "No org" }, { status: 403 });

  const from = req.nextUrl.searchParams.get("from") ?? thirtyDaysAgo();
  const to   = req.nextUrl.searchParams.get("to")   ?? today();

  const [vendors, costCenters] = await Promise.all([
    getSpendByProvider(member.org_id, from, to),
    getSpendByCostCenter(member.org_id, from, to),
  ]);

  const lines: string[] = [];

  // ── Section 1: Vendor Spend ──────────────────────────────────────────────
  lines.push(`Prism AI FinOps Report — Generated ${fmtDate()}`);
  lines.push(`Period: ${from.slice(0, 10)} to ${to.slice(0, 10)}`);
  lines.push("");
  lines.push("=== VENDOR SPEND ===");
  lines.push(row("Provider", "Total Spend (USD)", "Requests", "Total Tokens", "Cost per 1M Tokens", "% of Total"));

  const totalVendorCost = vendors.reduce((s, v) => s + v.total_cost_usd, 0);
  for (const v of vendors) {
    const pct = totalVendorCost > 0 ? ((v.total_cost_usd / totalVendorCost) * 100).toFixed(1) + "%" : "—";
    lines.push(row(
      v.provider,
      v.total_cost_usd.toFixed(6),
      v.total_requests,
      v.total_tokens,
      v.cost_per_1m_tokens.toFixed(4),
      pct,
    ));
  }
  lines.push(row("TOTAL", totalVendorCost.toFixed(6), "", "", "", "100%"));

  // ── Section 2: Cost Centers ───────────────────────────────────────────────
  lines.push("");
  lines.push("=== COST CENTER CHARGEBACK ===");
  lines.push(row("Cost Center", "Total Spend (USD)", "Requests", "Total Tokens", "% of Total"));

  const totalCcCost = costCenters.reduce((s, c) => s + c.cost_usd, 0);
  for (const c of costCenters) {
    const pct = totalCcCost > 0 ? ((c.cost_usd / totalCcCost) * 100).toFixed(1) + "%" : "—";
    lines.push(row(c.cost_center, c.cost_usd.toFixed(6), c.requests, c.total_tokens, pct));
  }

  if (costCenters.length === 0) {
    lines.push(row("(no cost center tags found — add PRISM_COST_CENTER env var to services)"));
  }

  lines.push("");
  lines.push("Generated by Prism — https://useprism.dev");

  const csv = lines.join("\n");

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type":        "text/csv",
      "Content-Disposition": `attachment; filename="prism-finops-${fmtDate()}.csv"`,
    },
  });
}
